import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Common/Footer";
import Script from "next/script";
import React, { Suspense } from "react";
import MixpanelProvider from "@/components/MixpanelProvider.client";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Favicon */}
        <link rel="icon" href="/logos/logo.svg" type="image/svg+xml" />
        <link rel="apple-touch-icon" href="/logos/logo-og.png" />
        {/* Open Graph for WhatsApp/social previews */}
        <meta property="og:title" content="Safari Sutra | Tour & Travel Agency in India" />
        <meta property="og:description" content="Safari Sutra offers unforgettable travel experiences across India and beyond." />
        <meta property="og:image" content="/logos/logo-og.png" />
        <meta property="og:url" content="https://thesafarisutra.com/" />
        <meta property="og:type" content="website" />
        {/* Twitter Card for completeness */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:image" content="/logos/logo-og.png" />

        {/* Google Tag Manager (head) - load before interactive */}
        <Script
          id="gtm-head"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MJGCDC3H');`,
          }}
        />

        {/* gtag.js */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-H704RB7X8M"
          strategy="afterInteractive"
        />
        <Script
          id="gtag-config"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-H704RB7X8M');`,
          }}
        />

        {/* Google tag (gtag.js) event - delayed navigation helper */}
        <Script
          id="gtag-send-event"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
  // Helper function to delay opening a URL until a gtag event is sent.
  // Call it in response to an action that should navigate to a URL.
  function gtagSendEvent(url) {
    var callback = function () {
      if (typeof url === 'string') {
        window.location = url;
      }
    };
    if (typeof gtag === 'function') {
      gtag('event', 'conversion_event_contact', {
        'event_callback': callback,
        'event_timeout': 2000
      });
    } else {
      // fallback: navigate after timeout
      setTimeout(callback, 2000);
    }
  }`,
          }}
        />

        {/* Meta Pixel */}
        <Script
          id="fb-pixel"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window, document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '731519309797706');
fbq('track', 'PageView');`,
          }}
        />

        {/* shown.io metrics script */}
        <Script
          id="shown-metrics"
          src="https://shown.io/metrics/Er0Ljw7o81"
          strategy="afterInteractive"
          defer
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* GTM & Pixel noscript fallbacks (must be immediately under <body>) */}
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-MJGCDC3H"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          />
        </noscript>
        <noscript>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            height="1"
            width="1"
            style={{ display: "none" }}
            src="https://www.facebook.com/tr?id=731519309797706&ev=PageView&noscript=1"
            alt="fb-pixel-noscript"
          />
        </noscript>

        {/* mounts Mixpanel client on every page (wrapped in Suspense so next can SSR bail out) */}
        <Suspense fallback={null}>
          <MixpanelProvider />
        </Suspense>
        {children}
        <Footer />
      </body>
    </html>
  );
}
